# Generated by Django 4.2.1 on 2023-06-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_buyer_pic4_alter_product_pic1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyer",
            old_name="pic4",
            new_name="pic",
        ),
    ]
