# Generated by Django 4.2.1 on 2023-06-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_alter_buyer_addressline1_alter_buyer_addressline2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyer",
            old_name="addressline1",
            new_name="address1",
        ),
        migrations.RenameField(
            model_name="buyer",
            old_name="addressline2",
            new_name="address2",
        ),
        migrations.RenameField(
            model_name="buyer",
            old_name="addressline3",
            new_name="address3",
        ),
    ]
