# Generated by Django 4.2.1 on 2023-07-04 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="name",
            new_name="product",
        ),
    ]
