# Generated by Django 4.2.1 on 2023-07-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0008_checkout"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="orderstatus",
            field=models.IntegerField(
                choices=[
                    (0, "Order Placed"),
                    (1, "Not Packed"),
                    (2, "Packed"),
                    (3, "Ready TO Ship"),
                    (4, "Shipped"),
                    (5, "Out For Delivery"),
                    (6, "Delivered"),
                    (7, "Cancelled"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="paymentmode",
            field=models.IntegerField(
                choices=[(0, "Cash On Delivery"), (1, "Netbanking")], default=0
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="paymentstatus",
            field=models.IntegerField(choices=[(0, "Pending"), (1, "Done")], default=0),
        ),
        migrations.CreateModel(
            name="CheckoutProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.checkout",
                    ),
                ),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.product",
                    ),
                ),
            ],
        ),
    ]
