# Generated by Django 4.2.1 on 2023-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0010_checkoutproducts_qty_checkoutproducts_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Active"), (1, "Solved")], default=0
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
