# Generated by Django 4.2.1 on 2023-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0012_buyer_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="paymentmode",
            field=models.IntegerField(
                choices=[(0, "COD"), (1, "Netbanking")], default=0
            ),
        ),
    ]
